//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedTechVpn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VpnConnection
    {
        public int Id { get; set; }
        public string Hostname { get; set; }
        public int Port { get; set; }
        public bool IsActive { get; set; }
    }
}
